# Generated by Django 4.0 on 2021-12-16 12:30

from django.db import migrations, models
import image_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_profile_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.IntegerField(validators=[image_app.validators.validate_no]),
        ),
    ]
